## To Run:   Run App, in Rstudio
## REFERENCE:   https://forum.posit.co/t/use-shiny-to-choose-column-equality-and-value-to-filter-by-conditions/47449
library(shiny)
library(tidyverse)


ui <- fluidPage(
  
  # Sidebar:   USER SELECTS
  # column input
  # boolean input
  # and value input
  sidebarLayout(
    sidebarPanel(
      fluidRow(column(4, selectInput("COLUMN", "Filter By:", choices = colnames(iris))),
               column(4, selectInput("CONDITION", "Boolean", choices = c("==", "!=", ">", "<"))),
               column(4, uiOutput("COL_VALUE")))
    ),
    
    # Show text generated by sidebar
    # use text in tidy pipeline to create subsetted dataframe
    mainPanel(
      verbatimTextOutput("as_text"),
      tableOutput("the_data")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  output$COL_VALUE <- renderUI({
    x <- iris %>% dplyr::select(!!sym(input$COLUMN))
    selectInput("VALUE", "Value", choices = x, selected = x[1])
  })
  
  # like a function
  filtering_string <- reactive ({
    #paste0("dplyr::filter(iris, ", input$COLUMN, " ", input$CONDITION, " ", input$VALUE, ")")
  f(ds = iris, quote(call(">", input$Sepal.Length, 7)))
    
  })
  
  output$as_text <- renderText({
    filtering_string()
  })
  
 # WORKS, but does not work when used in filter_string  
#  f = reactive({function(ds, col) ds |> dplyr::filter(!!col)})
  
#  f(ds=iris, col= quote(Sepal.Length > 7) )
  f = function(ds = iris, quote(call(">", input$Sepal.Length, 7)))
  
#  quote(call(">", Sepal.Length, 7))
#  eval(quote(call(">", Sepal.Length, 7)))
  
  # actual work
  output$the_data <- renderTable({
    eval(parse(text = filtering_string()))
  })
}

# Run the application 
shinyApp(ui = ui, server = server)#

