library(shiny)
library(purrr, dplyr, tibble)

# REF: 
## https://forum.posit.co/t/use-shiny-to-choose-column-equality-and-value-to-filter-by-conditions/47449

## USER chooses criteria, ie 3 choices to form  boolean condition  (such as `col1 > 3`) 
## b/c shiny does not know col1 until user picks it, shiny must create UI

# PROBLEM:  before user does anything, what does filtering string look like?
ui <- fluidPage(
  
  # Sidebar with an input for column
  # boolean input
  # and value input
  sidebarLayout(
    sidebarPanel(
      fluidRow(column(4, selectInput("COLUMN", "Filter By:", choices = colnames(iris))),
               column(4, selectInput("CONDITION", "Boolean", choices = c("==", "!=", ">", "<"))),
               column(4, uiOutput("COL_VALUE")))
    ),
    
    # Show text generated by sidebar
    # use text in tidy pipeline to create subsetted dataframe
    mainPanel(
      verbatimTextOutput("as_text"),
      tableOutput("the_data")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  output$COL_VALUE <- renderUI({
    x <- iris %>% select(!!sym(input$COLUMN))
    selectInput("VALUE", "Value", choices = x, selected = x[1])
  })
  

  # runs too soon;   before output$COL_VALUE was set 
  filtering_string <- reactive({
    paste0("dplyr::filter(iris, ",
           input$COLUMN,
           " ",
           input$CONDITION,
           " ",
           input$VALUE,
           ")"
          )
  })
  
  output$as_text <- renderText({
    filtering_string()
  })
  
  
  output$the_data <- renderTable({
      eval(parse(text = filtering_string()))
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
